version: '3.8'

services:

  postgres-db:
    image: postgres:16.3-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: propoligas_persons
      POSTGRES_DB: propoligas_persons_db
      POSTGRES_PASSWORD: propoligas_persons123
    container_name: apppropoligas_ms_persons
    volumes:
      - ./containers/postgres:/var/lib/postgresql/data
    ports:
      - 15335:5432